name: Close Issues on Done Status

on:
    issues:
        types: [edited]
    project_card:
        types: [converted_column, moved_column_in_project]

jobs:
    close_issue:
        runs-on: ubuntu-latest
        steps:
            - name: Check if issue should be closed
              id: check_if_should_close
              run: |
                  if [[ $(curl -s -H "Authorization: Bearer ${{ secrets.TOKEN }}" -H "Accept: application/vnd.github.inertia-preview+json" ${{ github.event.project_card.url }} | jq -r '.project_column.name') == *"done"* ]]; then
                    echo "::set-output name=close_issue::true"
                  else
                    echo "::set-output name=close_issue::false"
                  fi
            - if: steps.check_if_should_close.outputs.close_issue == 'true'
              name: Close Issue
              uses: peter-evans/close-issue@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              with:
                  issue-number: "${{ github.event.issue.number }}"
                  comment: "Closing issue because its status label includes the string 'done'"
