name: Close Issues on Done Status

on:
    project_card:
        types: [moved]

jobs:
    close-issues:
        runs-on: ubuntu-latest
        steps:
            - name: Close issues
              uses: peter-evans/close-issue@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  status: done
                  close-comment: true
                  close-locked: true
                  close-title: "Issue closed automatically"
                  close-labels: "auto-closed"
                  move-project-to-column: "Done"
